name: passwordmanager
description: "Personal password manager"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  otp_repository:
    path: packages/otp_repository

  hive_flutter: ^1.1.0

  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/images/heckpass.png"
  adaptive_icon_background: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/images/heckpass.png

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900